WITH TOPN AS (
	SELECT
		O.INFOCODE,
		O.DSQTNAME,
		O.REGION,
		P.MARKETDATE,
		P.CLOSE_ * S.NUMSHRS AS MARKETCAP,
		ROW_NUMBER()  OVER (PARTITION BY O.REGION,P.MARKETDATE ORDER BY P.CLOSE_ * S.NUMSHRS DESC) AS MCAP_RANK
	FROM  DS2CTRYQTINFO O
		JOIN  DS2PRIMQTPRC P
		ON    P.INFOCODE = O.INFOCODE
		AND	P.MARKETDATE IN	(
			SELECT 	MAX(P1.MARKETDATE) 
			FROM 	DS2PRIMQTPRC P1
			WHERE  P1.INFOCODE = '46244' -- Returns the max of Trading dates of IBM Grouped by Year.
			GROUP  BY YEAR(P1.MARKETDATE),MONTH(P1.MARKETDATE))
   		JOIN  DS2NUMSHARES S
    	ON    S.INFOCODE = O.INFOCODE
    	AND   S.EVENTDATE = (
    		SELECT MAX(EVENTDATE) 
      		FROM DS2NUMSHARES 
      		WHERE INFOCODE = O.INFOCODE 
      		AND EVENTDATE <= P.MARKETDATE)        
	WHERE O.REGION = 'AU' --('AU','CA','DE','FR','IN','JP','GB')
	AND O.TYPECODE ='EQ'   --Equities
	AND  P.MARKETDATE >= '1979-01-01')
SELECT *
FROM TOPN T
JOIN DS2PRIMQTPRC P
	ON P.INFOCODE = T.INFOCODE
	AND YEAR(P.MARKETDATE) = YEAR(T.MARKETDATE)
	AND MONTH(P.MARKETDATE) = MONTH(T.MARKETDATE)
JOIN DS2PRIMQTRI R
	ON P.INFOCODE = R.INFOCODE
	AND P.MARKETDATE = R.MARKETDATE
WHERE MCAP_RANK <= 200
--ORDER BY T.REGION,P.MARKETDATE ASC